CREATE DATABASE `vis3`;

CREATE TABLE bingModel
(
objID INT(2) NOT NULL AUTO_INCREMENT,
obj TEXT NOT NULL,
cPointLat DECIMAL(11,9) NOT NULL,
cPointLong DECIMAL(11,9) NOT NULL,
gml TEXT NOT NULL,
nof INT(2) NOT NULL,
date DATE NOT NULL,
PRIMARY KEY(objID)
);


